
[project]
name = "transformer"
version = "0.1.0"
description = "Transformer implementation in PyTorch"
requires-python = ">=3.11"
authors = [
    { name = "Marko Cvjetko", email = "marko.cvjetko1@gmail.com" }
]
dependencies = [
    "torch",
    "datasets",
    "tqdm",
    "sacrebleu",
    "matplotlib",
    "lightning",
    "optuna",
    "optuna-dashboard",
    "optuna-integration[pytorch-lightning]",
    "tensorboard",
    "wandb",
    "submitit",
    "translate-toolkit",
    "lxml",
    "langid",
    "python-dotenv",
    "docling"

]

[project.optional-dependencies]
dev = ["ruff"]

[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
